// This file is auto-generated by @hey-api/openapi-ts

export const RegistrationDTOSchema = {
  type: 'object',
  properties: {
    firstname: {
      type: 'string',
      description: 'employee firstname',
    },
    lastname: {
      type: 'string',
      description: 'employee lastname',
    },
    dateOfBirth: {
      type: 'string',
      format: 'date',
    },
  },
} as const

export const CreationHolidayDTOSchema = {
  type: 'object',
  properties: {
    title: {
      type: 'string',
      description: 'holiday title',
    },
    type: {
      type: 'integer',
      format: 'int64',
      description: 'id of holiday type',
    },
    description: {
      type: 'string',
    },
    period: {
      $ref: '#/components/schemas/PeriodDTO',
    },
    dateOfBirth: {
      type: 'string',
      format: 'date',
    },
  },
} as const

export const RegistrationResponseDTOSchema = {
  type: 'object',
  properties: {
    employeeId: {
      type: 'integer',
      format: 'int64',
      description: 'created employee ID',
    },
    accessToken: {
      type: 'string',
    },
  },
} as const

export const EmployeeDTOSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      format: 'int64',
      description: 'identifier of employee',
    },
    password: {
      type: 'string',
      description: 'employee password',
    },
    firstname: {
      type: 'string',
      description: 'employee firstname',
    },
    lastname: {
      type: 'string',
      description: 'employee lastname',
    },
    email: {
      type: 'string',
      description: 'employee email',
    },
    dateOfBirth: {
      type: 'string',
      format: 'date',
      description: 'employee date of birth',
    },
    isActivated: {
      type: 'boolean',
      description: "the value is 'true' if the employee insert an existing email",
    },
    role: {
      $ref: '#/components/schemas/RoleDTO',
    },
  },
} as const

export const HolidayDTOSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      format: 'int64',
    },
    title: {
      type: 'string',
    },
    type: {
      $ref: '#/components/schemas/HolidayTypeDTO',
    },
    description: {
      type: 'string',
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
    },
    period: {
      $ref: '#/components/schemas/PeriodDTO',
    },
    status: {
      $ref: '#/components/schemas/HolidayStatusDTO',
    },
    createdBy: {
      $ref: '#/components/schemas/EmployeeDTO',
    },
  },
} as const

export const PeriodDTOSchema = {
  type: 'object',
  properties: {
    startDate: {
      type: 'string',
      format: 'date',
    },
    endDate: {
      type: 'string',
      format: 'date',
    },
  },
} as const

export const HolidayStatusDTOSchema = {
  type: 'string',
  enum: ['DRAFT', 'PUBLISH', 'APPROVED', 'VALIDATED', 'REFUSED', 'IN_PROGRESS', 'PASSED'],
} as const

export const HolidayTypeDTOSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      format: 'int64',
    },
    name: {
      type: 'string',
    },
    description: {
      type: 'string',
    },
  },
} as const

export const HolidayConfigDTOSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      format: 'int64',
    },
    description: {
      type: 'string',
    },
    numberOfTime: {
      type: 'integer',
      description: 'number of times leave can be requested over a year',
    },
    minimumOfDays: {
      type: 'integer',
      description: 'minimum duration of leave in days',
    },
    maximumOfDays: {
      type: 'integer',
      description: 'maximal duration of leave in days',
    },
    isActivate: {
      type: 'boolean',
    },
    holidayTypeId: {
      type: 'integer',
      format: 'int64',
      description: 'the identifier of holiday type concerning by this configuration',
    },
  },
} as const

export const NoticeStatusDTOSchema = {
  type: 'string',
  enum: ['OK', 'NOT_OK'],
} as const

export const AuthenticationRequestDTOSchema = {
  type: 'object',
  properties: {
    email: {
      type: 'string',
    },
    password: {
      type: 'string',
    },
  },
} as const

export const TokenDTOSchema = {
  type: 'object',
  properties: {
    value: {
      type: 'string',
    },
  },
} as const

export const NoticeDTOSchema = {
  type: 'object',
  properties: {
    type: {
      $ref: '#/components/schemas/NoticeStatusDTO',
    },
    description: {
      type: 'string',
    },
  },
} as const

export const ReasonDTOSchema = {
  type: 'object',
  properties: {
    value: {
      type: 'string',
    },
  },
} as const

export const RoleDTOSchema = {
  type: 'string',
  enum: ['EMPLOYEE', 'ADMIN', 'SUPER_ADMIN'],
} as const

export const PassWordDTOSchema = {
  type: 'object',
  properties: {
    value: {
      type: 'string',
    },
  },
} as const
