// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-axios'
import type {
  CreateSuperAdmin_Data,
  CreateSuperAdmin_Response,
  CreateAdmin_Data,
  CreateAdmin_Response,
  CreateEmployee_Data,
  CreateEmployee_Response,
  GetAllEmployees_Data,
  GetAllEmployees_Response,
  DeleteEmployeeById_Data,
  DeleteEmployeeById_Response,
  GetEmployeeById_Data,
  GetEmployeeById_Response,
  UpdateEmployee_Data,
  CreateHoliday_Data,
  CreateHoliday_Response,
  GetAllHolidays_Data,
  GetAllHolidays_Response,
  DeleteHolidayById_Data,
  DeleteHolidayById_Response,
  GetHolidayById_Data,
  GetHolidayById_Response,
  UpdateHoliday_Data,
  GetNoticesByHoliday_Data,
  NoticeHoliday_Data,
  PublishHoliday_Data,
  UnpublishedHoliday_Data,
  ApprovedHoliday_Data,
  ApprovedHoliday_Response,
  RejectHoliday_Data,
  RejectHoliday_Response,
  GetAllHolidayTypes_Data,
  GetAllHolidayTypes_Response,
  CreateHolidayType_Data,
  CreateHolidayType_Response,
  DeleteHolidayTypeById_Data,
  DeleteHolidayTypeById_Response,
  GetHolidayTypeById_Data,
  GetHolidayTypeById_Response,
  UpdateHolidayType_Data,
  GetAllHolidayConfigs_Data,
  GetAllHolidayConfigs_Response,
  CreateHolidayConfig_Data,
  CreateHolidayConfig_Response,
  GetHolidayConfigById_Data,
  GetHolidayConfigById_Response,
  GetAllHolidayConfigByHolidayType_Data,
  GetAllHolidayConfigByHolidayType_Response,
  ActivateHolidayConfig_Data,
  ActivateHolidayConfig_Response,
  DeactivateHolidayConfig_Data,
  DeactivateHolidayConfig_Response,
  Authenticate_Data,
  Authenticate_Response,
  GetAllMyHolidays_Data,
  GetAllMyHolidays_Response,
  GetActivatedHolidayConfigByHolidayTypeId_Data,
  GetActivatedHolidayConfigByHolidayTypeId_Response,
  GetPassword_Data,
  GetPassword_Response,
  UpdatePassword_Data,
} from './types.gen'
import { client as _heyApiClient } from './client.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
}

export class AdminService {
  /**
   * Create the super admin in the app
   * Create the super admin of app. He is an employee by default
   */
  public static createSuperAdmin<ThrowOnError extends boolean = false>(
    options: Options<CreateSuperAdmin_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<CreateSuperAdmin_Response, unknown, ThrowOnError>(
      {
        url: '/admin/registration',
        ...options,
        headers: {
          'Content-Type': 'application/json',
          ...options?.headers,
        },
      },
    )
  }

  /**
   * Create an admin in the app
   * create an admin as super admin
   */
  public static createAdmin<ThrowOnError extends boolean = false>(
    options: Options<CreateAdmin_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<CreateAdmin_Response, unknown, ThrowOnError>({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/admin/add',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    })
  }

  /**
   * Create an employee in the app
   * create an employee as super admin or admin
   */
  public static createEmployee<ThrowOnError extends boolean = false>(
    options: Options<CreateEmployee_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<CreateEmployee_Response, unknown, ThrowOnError>({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/admin/employee/add',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    })
  }

  /**
   * get all employees
   * get all employees present in the app
   */
  public static getAllEmployees<ThrowOnError extends boolean = false>(
    options?: Options<GetAllEmployees_Data, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<GetAllEmployees_Response, unknown, ThrowOnError>({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/admin/employee/all',
      ...options,
    })
  }
}

export class EmployeeService {
  /**
   * Delete employee by id
   * Delete employee by id
   */
  public static deleteEmployeeById<ThrowOnError extends boolean = false>(
    options: Options<DeleteEmployeeById_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      DeleteEmployeeById_Response,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/employee/{employeeId}',
      ...options,
    })
  }

  /**
   * Get Employee by id
   * Get Employee by id. only the super admin or admin and the user account
   */
  public static getEmployeeById<ThrowOnError extends boolean = false>(
    options: Options<GetEmployeeById_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<GetEmployeeById_Response, unknown, ThrowOnError>({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/employee/{employeeId}',
      ...options,
    })
  }

  /**
   * update a Employee
   * update a Employee
   */
  public static updateEmployee<ThrowOnError extends boolean = false>(
    options: Options<UpdateEmployee_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<unknown, unknown, ThrowOnError>({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/employee/{employeeId}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    })
  }

  /**
   * get employee password
   * get employee password
   */
  public static getPassword<ThrowOnError extends boolean = false>(
    options?: Options<GetPassword_Data, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<GetPassword_Response, unknown, ThrowOnError>({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/employee/password',
      ...options,
    })
  }

  /**
   * update an employee password
   * update an employee password
   */
  public static updatePassword<ThrowOnError extends boolean = false>(
    options: Options<UpdatePassword_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<unknown, unknown, ThrowOnError>({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/employee/password',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    })
  }
}

export class HolidayService {
  /**
   * Create a Holiday in the app
   * create a Holiday
   */
  public static createHoliday<ThrowOnError extends boolean = false>(
    options: Options<CreateHoliday_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<CreateHoliday_Response, unknown, ThrowOnError>({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/holiday',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    })
  }

  /**
   * get all Holidays
   * get all Holidays present in the app
   */
  public static getAllHolidays<ThrowOnError extends boolean = false>(
    options?: Options<GetAllHolidays_Data, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<GetAllHolidays_Response, unknown, ThrowOnError>({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/holiday/all',
      ...options,
    })
  }

  /**
   * Delete holiday by id
   * Delete holiday by id
   */
  public static deleteHolidayById<ThrowOnError extends boolean = false>(
    options: Options<DeleteHolidayById_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      DeleteHolidayById_Response,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/holiday/{holidayId}',
      ...options,
    })
  }

  /**
   * Get Holiday by id
   * Get Holiday by id. only the super admin or admin and the user account
   */
  public static getHolidayById<ThrowOnError extends boolean = false>(
    options: Options<GetHolidayById_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<GetHolidayById_Response, unknown, ThrowOnError>({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/holiday/{holidayId}',
      ...options,
    })
  }

  /**
   * update a Holiday
   * update a Holiday
   */
  public static updateHoliday<ThrowOnError extends boolean = false>(
    options: Options<UpdateHoliday_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<unknown, unknown, ThrowOnError>({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/holiday/{holidayId}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    })
  }

  /**
   * Get all notices by holiday
   * Get all notices by holiday
   */
  public static getNoticesByHoliday<ThrowOnError extends boolean = false>(
    options: Options<GetNoticesByHoliday_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/holiday/{holidayId}/notice',
      ...options,
    })
  }

  /**
   * notice a Holiday
   * notice a Holiday
   */
  public static noticeHoliday<ThrowOnError extends boolean = false>(
    options: Options<NoticeHoliday_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<unknown, unknown, ThrowOnError>({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/holiday/{holidayId}/notice',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    })
  }

  /**
   * publish a Holiday
   * publish a Holiday
   */
  public static publishHoliday<ThrowOnError extends boolean = false>(
    options: Options<PublishHoliday_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<unknown, unknown, ThrowOnError>({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/publish/{holidayId}',
      ...options,
    })
  }

  /**
   * unpublished a Holiday
   * unpublished a Holiday
   */
  public static unpublishedHoliday<ThrowOnError extends boolean = false>(
    options: Options<UnpublishedHoliday_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<unknown, unknown, ThrowOnError>({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/unpublished/{holidayId}',
      ...options,
    })
  }

  /**
   * approved a Holiday
   * approved a Holiday
   */
  public static approvedHoliday<ThrowOnError extends boolean = false>(
    options: Options<ApprovedHoliday_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<ApprovedHoliday_Response, unknown, ThrowOnError>({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/validate/{holidayId}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    })
  }

  /**
   * reject a Holiday
   * reject a Holiday
   */
  public static rejectHoliday<ThrowOnError extends boolean = false>(
    options: Options<RejectHoliday_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<RejectHoliday_Response, unknown, ThrowOnError>({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/reject/{holidayId}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    })
  }

  /**
   * get all HolidayType
   * get all HolidayType present in the app
   */
  public static getAllHolidayTypes<ThrowOnError extends boolean = false>(
    options?: Options<GetAllHolidayTypes_Data, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      GetAllHolidayTypes_Response,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/holiday/type',
      ...options,
    })
  }

  /**
   * Create a HolidayType in the app
   * create a HolidayType
   */
  public static createHolidayType<ThrowOnError extends boolean = false>(
    options: Options<CreateHolidayType_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      CreateHolidayType_Response,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/holiday/type',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    })
  }

  /**
   * Delete holidayType by id
   * Delete holidayType by id
   */
  public static deleteHolidayTypeById<ThrowOnError extends boolean = false>(
    options: Options<DeleteHolidayTypeById_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      DeleteHolidayTypeById_Response,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/holiday/type/{holidayTypeId}',
      ...options,
    })
  }

  /**
   * Get HolidayType by id
   * Get HolidayType by id. only the super admin or admin and the user account
   */
  public static getHolidayTypeById<ThrowOnError extends boolean = false>(
    options: Options<GetHolidayTypeById_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      GetHolidayTypeById_Response,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/holiday/type/{holidayTypeId}',
      ...options,
    })
  }

  /**
   * update a HolidayType
   * update a HolidayType
   */
  public static updateHolidayType<ThrowOnError extends boolean = false>(
    options: Options<UpdateHolidayType_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<unknown, unknown, ThrowOnError>({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/holiday/type/{holidayTypeId}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    })
  }

  /**
   * get all my Holidays
   * get all my Holidays
   */
  public static getAllMyHolidays<ThrowOnError extends boolean = false>(
    options?: Options<GetAllMyHolidays_Data, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<GetAllMyHolidays_Response, unknown, ThrowOnError>(
      {
        security: [
          {
            scheme: 'bearer',
            type: 'http',
          },
        ],
        url: '/holiday/my-holidays',
        ...options,
      },
    )
  }
}

export class HolidayConfigService {
  /**
   * get all HolidayConfigS
   * get all HolidayConfig present in the app
   */
  public static getAllHolidayConfigs<ThrowOnError extends boolean = false>(
    options?: Options<GetAllHolidayConfigs_Data, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      GetAllHolidayConfigs_Response,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/config/holiday',
      ...options,
    })
  }

  /**
   * Create a HolidayConfig in the app
   * create a HolidayConfig
   */
  public static createHolidayConfig<ThrowOnError extends boolean = false>(
    options: Options<CreateHolidayConfig_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      CreateHolidayConfig_Response,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/config/holiday',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    })
  }

  /**
   * Get HolidayConfig by id
   * Get HolidayConfig by id. only the super admin or admin and the user account
   */
  public static getHolidayConfigById<ThrowOnError extends boolean = false>(
    options: Options<GetHolidayConfigById_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      GetHolidayConfigById_Response,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/config/{holidayConfigId}',
      ...options,
    })
  }

  /**
   * Get HolidayConfig by holiday type id
   * Get HolidayConfig by holiday type id
   */
  public static getAllHolidayConfigByHolidayType<ThrowOnError extends boolean = false>(
    options: Options<GetAllHolidayConfigByHolidayType_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      GetAllHolidayConfigByHolidayType_Response,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/holiday-type/{holidayTypeId}/config',
      ...options,
    })
  }

  /**
   * activate a HolidayConfig
   * activate a HolidayConfig
   */
  public static activateHolidayConfig<ThrowOnError extends boolean = false>(
    options: Options<ActivateHolidayConfig_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<
      ActivateHolidayConfig_Response,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/config/holiday/{holidayConfigId}/activate',
      ...options,
    })
  }

  /**
   * deactivate a HolidayConfig
   * deactivate a HolidayConfig
   */
  public static deactivateHolidayConfig<ThrowOnError extends boolean = false>(
    options: Options<DeactivateHolidayConfig_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<
      DeactivateHolidayConfig_Response,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/config/holiday/{holidayConfigId}/deactivate',
      ...options,
    })
  }

  /**
   * get activated holiday by holidayType
   * get activated holiday by holidayType
   */
  public static getActivatedHolidayConfigByHolidayTypeId<ThrowOnError extends boolean = false>(
    options: Options<GetActivatedHolidayConfigByHolidayTypeId_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      GetActivatedHolidayConfigByHolidayTypeId_Response,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/holiday-type/{holidayTypeId}/config/active',
      ...options,
    })
  }
}

export class AuthenticationService {
  /**
   * authenticate user
   * get access token after identified the user
   */
  public static authenticate<ThrowOnError extends boolean = false>(
    options: Options<Authenticate_Data, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<Authenticate_Response, unknown, ThrowOnError>({
      url: '/auth/authenticate',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    })
  }
}
