// This file is auto-generated by @hey-api/openapi-ts

export type RegistrationDTO = {
  /**
   * employee firstname
   */
  firstname?: string
  /**
   * employee lastname
   */
  lastname?: string
  dateOfBirth?: string
}

export type CreationHolidayDTO = {
  /**
   * holiday title
   */
  title?: string
  /**
   * id of holiday type
   */
  type?: number
  description?: string
  period?: PeriodDTO
  dateOfBirth?: string
}

export type RegistrationResponseDTO = {
  /**
   * created employee ID
   */
  employeeId?: number
  accessToken?: string
}

export type EmployeeDTO = {
  /**
   * identifier of employee
   */
  id?: number
  /**
   * employee password
   */
  password?: string
  /**
   * employee firstname
   */
  firstname?: string
  /**
   * employee lastname
   */
  lastname?: string
  /**
   * employee email
   */
  email?: string
  /**
   * employee date of birth
   */
  dateOfBirth?: string
  /**
   * the value is 'true' if the employee insert an existing email
   */
  isActivated?: boolean
  role?: RoleDTO
}

export type HolidayDTO = {
  id?: number
  title?: string
  type?: HolidayTypeDTO
  description?: string
  createdAt?: string
  period?: PeriodDTO
  status?: HolidayStatusDTO
  createdBy?: EmployeeDTO
}

export type PeriodDTO = {
  startDate?: string
  endDate?: string
}

export type HolidayStatusDTO =
  | 'DRAFT'
  | 'PUBLISH'
  | 'APPROVED'
  | 'VALIDATED'
  | 'REFUSED'
  | 'IN_PROGRESS'
  | 'PASSED'

export type HolidayTypeDTO = {
  id?: number
  name?: string
  description?: string
}

export type HolidayConfigDTO = {
  id?: number
  description?: string
  /**
   * number of times leave can be requested over a year
   */
  numberOfTime?: number
  /**
   * minimum duration of leave in days
   */
  minimumOfDays?: number
  /**
   * maximal duration of leave in days
   */
  maximumOfDays?: number
  isActivate?: boolean
  /**
   * the identifier of holiday type concerning by this configuration
   */
  holidayTypeId?: number
}

export type NoticeStatusDTO = 'OK' | 'NOT_OK'

export type AuthenticationRequestDTO = {
  email?: string
  password?: string
}

export type TokenDTO = {
  value?: string
}

export type NoticeDTO = {
  type?: NoticeStatusDTO
  description?: string
}

export type ReasonDTO = {
  value?: string
}

export type RoleDTO = 'EMPLOYEE' | 'ADMIN' | 'SUPER_ADMIN'

export type PassWordDTO = {
  value?: string
}

export type CreateSuperAdmin_Data = {
  /**
   * registration data that need to be use for create employee
   */
  body: RegistrationDTO
  path?: never
  query?: never
  url: '/admin/registration'
}

export type CreateSuperAdmin_Responses = {
  /**
   * successful operation
   */
  201: RegistrationResponseDTO
}

export type CreateSuperAdmin_Response = CreateSuperAdmin_Responses[keyof CreateSuperAdmin_Responses]

export type CreateAdmin_Data = {
  /**
   * registration data that need to be use for create employee
   */
  body: RegistrationDTO
  path?: never
  query?: never
  url: '/admin/add'
}

export type CreateAdmin_Responses = {
  /**
   * successful operation
   */
  201: number
}

export type CreateAdmin_Response = CreateAdmin_Responses[keyof CreateAdmin_Responses]

export type CreateEmployee_Data = {
  /**
   * registration data that need to be use for create employee
   */
  body: RegistrationDTO
  path?: never
  query?: never
  url: '/admin/employee/add'
}

export type CreateEmployee_Responses = {
  /**
   * successful operation
   */
  201: number
}

export type CreateEmployee_Response = CreateEmployee_Responses[keyof CreateEmployee_Responses]

export type GetAllEmployees_Data = {
  body?: never
  path?: never
  query?: never
  url: '/admin/employee/all'
}

export type GetAllEmployees_Responses = {
  /**
   * successful operation
   */
  200: Array<EmployeeDTO>
}

export type GetAllEmployees_Response = GetAllEmployees_Responses[keyof GetAllEmployees_Responses]

export type DeleteEmployeeById_Data = {
  body?: never
  path: {
    /**
     * The id of the employee to delete
     */
    employeeId: number
  }
  query?: never
  url: '/employee/{employeeId}'
}

export type DeleteEmployeeById_Responses = {
  /**
   * successful operation
   */
  204: void
}

export type DeleteEmployeeById_Response =
  DeleteEmployeeById_Responses[keyof DeleteEmployeeById_Responses]

export type GetEmployeeById_Data = {
  body?: never
  path: {
    /**
     * employee ID to retrieve
     */
    employeeId: number
  }
  query?: never
  url: '/employee/{employeeId}'
}

export type GetEmployeeById_Responses = {
  /**
   * successful operation
   */
  200: EmployeeDTO
}

export type GetEmployeeById_Response = GetEmployeeById_Responses[keyof GetEmployeeById_Responses]

export type UpdateEmployee_Data = {
  /**
   * Employee object that need to be update
   */
  body: EmployeeDTO
  path: {
    /**
     * employee ID
     */
    employeeId: number
  }
  query?: never
  url: '/employee/{employeeId}'
}

export type UpdateEmployee_Responses = {
  /**
   * successful operation
   */
  201: unknown
}

export type CreateHoliday_Data = {
  /**
   * object that need to be use for create Holiday
   */
  body: CreationHolidayDTO
  path?: never
  query?: never
  url: '/holiday'
}

export type CreateHoliday_Responses = {
  /**
   * successful operation
   */
  201: number
}

export type CreateHoliday_Response = CreateHoliday_Responses[keyof CreateHoliday_Responses]

export type GetAllHolidays_Data = {
  body?: never
  path?: never
  query?: never
  url: '/holiday/all'
}

export type GetAllHolidays_Responses = {
  /**
   * successful operation
   */
  200: Array<HolidayDTO>
}

export type GetAllHolidays_Response = GetAllHolidays_Responses[keyof GetAllHolidays_Responses]

export type DeleteHolidayById_Data = {
  body?: never
  path: {
    /**
     * The id of the holiday to delete
     */
    holidayId: number
  }
  query?: never
  url: '/holiday/{holidayId}'
}

export type DeleteHolidayById_Responses = {
  /**
   * successful operation
   */
  204: void
}

export type DeleteHolidayById_Response =
  DeleteHolidayById_Responses[keyof DeleteHolidayById_Responses]

export type GetHolidayById_Data = {
  body?: never
  path: {
    /**
     * holiday ID to retrieve
     */
    holidayId: number
  }
  query?: never
  url: '/holiday/{holidayId}'
}

export type GetHolidayById_Responses = {
  /**
   * successful operation
   */
  200: HolidayDTO
}

export type GetHolidayById_Response = GetHolidayById_Responses[keyof GetHolidayById_Responses]

export type UpdateHoliday_Data = {
  /**
   * Holiday object that need to be update
   */
  body: HolidayDTO
  path: {
    /**
     * employee ID
     */
    holidayId: number
  }
  query?: never
  url: '/holiday/{holidayId}'
}

export type UpdateHoliday_Responses = {
  /**
   * successful operation
   */
  201: unknown
}

export type GetNoticesByHoliday_Data = {
  body?: never
  path: {
    /**
     * holiday ID to get all notices
     */
    holidayId: number
  }
  query?: never
  url: '/holiday/{holidayId}/notice'
}

export type GetNoticesByHoliday_Responses = {
  /**
   * successful operation
   */
  200: unknown
}

export type NoticeHoliday_Data = {
  /**
   * Holiday object that need to be notice
   */
  body: NoticeDTO
  path: {
    /**
     * holiday ID
     */
    holidayId: number
  }
  query?: never
  url: '/holiday/{holidayId}/notice'
}

export type NoticeHoliday_Responses = {
  /**
   * successful operation
   */
  201: unknown
}

export type PublishHoliday_Data = {
  body?: never
  path: {
    /**
     * holiday ID
     */
    holidayId: number
  }
  query?: never
  url: '/publish/{holidayId}'
}

export type PublishHoliday_Responses = {
  /**
   * successful operation
   */
  201: unknown
}

export type UnpublishedHoliday_Data = {
  body?: never
  path: {
    /**
     * holiday ID
     */
    holidayId: number
  }
  query?: never
  url: '/unpublished/{holidayId}'
}

export type UnpublishedHoliday_Responses = {
  /**
   * successful operation
   */
  201: unknown
}

export type ApprovedHoliday_Data = {
  /**
   * the reason of the agreement
   */
  body?: ReasonDTO
  path: {
    /**
     * holiday ID to approved
     */
    holidayId: number
  }
  query?: never
  url: '/validate/{holidayId}'
}

export type ApprovedHoliday_Responses = {
  /**
   * successful operation
   */
  204: void
}

export type ApprovedHoliday_Response = ApprovedHoliday_Responses[keyof ApprovedHoliday_Responses]

export type RejectHoliday_Data = {
  /**
   * reason of the rejection
   */
  body?: ReasonDTO
  path: {
    /**
     * holiday ID to approved
     */
    holidayId: number
  }
  query?: never
  url: '/reject/{holidayId}'
}

export type RejectHoliday_Responses = {
  /**
   * successful operation
   */
  204: void
}

export type RejectHoliday_Response = RejectHoliday_Responses[keyof RejectHoliday_Responses]

export type GetAllHolidayTypes_Data = {
  body?: never
  path?: never
  query?: never
  url: '/holiday/type'
}

export type GetAllHolidayTypes_Responses = {
  /**
   * successful operation
   */
  200: Array<HolidayTypeDTO>
}

export type GetAllHolidayTypes_Response =
  GetAllHolidayTypes_Responses[keyof GetAllHolidayTypes_Responses]

export type CreateHolidayType_Data = {
  /**
   * object that need to be use for create Holiday
   */
  body: HolidayTypeDTO
  path?: never
  query?: never
  url: '/holiday/type'
}

export type CreateHolidayType_Responses = {
  /**
   * successful operation
   */
  201: number
}

export type CreateHolidayType_Response =
  CreateHolidayType_Responses[keyof CreateHolidayType_Responses]

export type DeleteHolidayTypeById_Data = {
  body?: never
  path: {
    /**
     * The id of the holidayType to delete
     */
    holidayTypeId: number
  }
  query?: never
  url: '/holiday/type/{holidayTypeId}'
}

export type DeleteHolidayTypeById_Responses = {
  /**
   * successful operation
   */
  204: void
}

export type DeleteHolidayTypeById_Response =
  DeleteHolidayTypeById_Responses[keyof DeleteHolidayTypeById_Responses]

export type GetHolidayTypeById_Data = {
  body?: never
  path: {
    /**
     * holiday ID to retrieve
     */
    holidayTypeId: number
  }
  query?: never
  url: '/holiday/type/{holidayTypeId}'
}

export type GetHolidayTypeById_Responses = {
  /**
   * successful operation
   */
  200: HolidayTypeDTO
}

export type GetHolidayTypeById_Response =
  GetHolidayTypeById_Responses[keyof GetHolidayTypeById_Responses]

export type UpdateHolidayType_Data = {
  /**
   * holidayType object that need to be update
   */
  body: HolidayTypeDTO
  path: {
    /**
     * holidayType ID
     */
    holidayTypeId: number
  }
  query?: never
  url: '/holiday/type/{holidayTypeId}'
}

export type UpdateHolidayType_Responses = {
  /**
   * successful operation
   */
  201: unknown
}

export type GetAllHolidayConfigs_Data = {
  body?: never
  path?: never
  query?: never
  url: '/config/holiday'
}

export type GetAllHolidayConfigs_Responses = {
  /**
   * successful operation
   */
  200: Array<HolidayConfigDTO>
}

export type GetAllHolidayConfigs_Response =
  GetAllHolidayConfigs_Responses[keyof GetAllHolidayConfigs_Responses]

export type CreateHolidayConfig_Data = {
  /**
   * object that need to be use for create HolidayConfig
   */
  body: HolidayConfigDTO
  path?: never
  query?: never
  url: '/config/holiday'
}

export type CreateHolidayConfig_Responses = {
  /**
   * successful operation
   */
  201: number
}

export type CreateHolidayConfig_Response =
  CreateHolidayConfig_Responses[keyof CreateHolidayConfig_Responses]

export type GetHolidayConfigById_Data = {
  body?: never
  path: {
    /**
     * HolidayConfig ID to retrieve
     */
    holidayConfigId: number
  }
  query?: never
  url: '/config/{holidayConfigId}'
}

export type GetHolidayConfigById_Responses = {
  /**
   * successful operation
   */
  200: HolidayConfigDTO
}

export type GetHolidayConfigById_Response =
  GetHolidayConfigById_Responses[keyof GetHolidayConfigById_Responses]

export type GetAllHolidayConfigByHolidayType_Data = {
  body?: never
  path: {
    /**
     * HolidayConfig ID to retrieve
     */
    holidayTypeId: number
  }
  query?: never
  url: '/holiday-type/{holidayTypeId}/config'
}

export type GetAllHolidayConfigByHolidayType_Responses = {
  /**
   * successful operation
   */
  200: unknown
}

export type ActivateHolidayConfig_Data = {
  body?: never
  path: {
    /**
     * holiday config ID
     */
    holidayConfigId: number
  }
  query?: never
  url: '/config/holiday/{holidayConfigId}/activate'
}

export type ActivateHolidayConfig_Responses = {
  /**
   * successful operation
   */
  204: void
}

export type ActivateHolidayConfig_Response =
  ActivateHolidayConfig_Responses[keyof ActivateHolidayConfig_Responses]

export type DeactivateHolidayConfig_Data = {
  body?: never
  path: {
    /**
     * holiday config ID
     */
    holidayConfigId: number
  }
  query?: never
  url: '/config/holiday/{holidayConfigId}/deactivate'
}

export type DeactivateHolidayConfig_Responses = {
  /**
   * successful operation
   */
  204: void
}

export type DeactivateHolidayConfig_Response =
  DeactivateHolidayConfig_Responses[keyof DeactivateHolidayConfig_Responses]

export type Authenticate_Data = {
  /**
   * object that need to be use for create HolidayConfig
   */
  body: AuthenticationRequestDTO
  path?: never
  query?: never
  url: '/auth/authenticate'
}

export type Authenticate_Responses = {
  /**
   * successful operation
   */
  201: TokenDTO
}

export type Authenticate_Response = Authenticate_Responses[keyof Authenticate_Responses]

export type GetAllMyHolidays_Data = {
  body?: never
  path?: never
  query?: never
  url: '/holiday/my-holidays'
}

export type GetAllMyHolidays_Responses = {
  /**
   * successful operation
   */
  200: Array<HolidayDTO>
}

export type GetAllMyHolidays_Response = GetAllMyHolidays_Responses[keyof GetAllMyHolidays_Responses]

export type GetActivatedHolidayConfigByHolidayTypeId_Data = {
  body?: never
  path: {
    /**
     * holiday type ID
     */
    holidayTypeId: number
  }
  query?: never
  url: '/holiday-type/{holidayTypeId}/config/active'
}

export type GetActivatedHolidayConfigByHolidayTypeId_Responses = {
  /**
   * successful operation
   */
  200: HolidayConfigDTO
}

export type GetActivatedHolidayConfigByHolidayTypeId_Response =
  GetActivatedHolidayConfigByHolidayTypeId_Responses[keyof GetActivatedHolidayConfigByHolidayTypeId_Responses]

export type GetPassword_Data = {
  body?: never
  path?: never
  query?: never
  url: '/employee/password'
}

export type GetPassword_Responses = {
  /**
   * successful operation
   */
  200: PassWordDTO
}

export type GetPassword_Response = GetPassword_Responses[keyof GetPassword_Responses]

export type UpdatePassword_Data = {
  /**
   * Holiday object that need to be update
   */
  body: PassWordDTO
  path?: never
  query?: never
  url: '/employee/password'
}

export type UpdatePassword_Responses = {
  /**
   * successful operation
   */
  201: unknown
}

export type ClientOptions = {
  baseURL: 'http://localhost:8080/api/leavemanager/v1' | (string & {})
}
